leapdao/leap-node

- index.js
- src/block/updatePeriod.js
- src/period/checkBridge.js
- src/txHelpers/activateSlot.js
- src/utils/getAuctionedByAddr.js
- src/utils/index.js
if some-one buys a slot, it should be activated once the period height has advanced
> slot activation

- README.md
- index.js
- package.json
- src/block/addBlock.js
- src/block/updatePeriod.js
- src/block/updateValidators.js
- src/block/updateValidators.test.js
- src/debug.js
- src/eventsRelay/ContractEventsSubscription.js
- src/eventsRelay/ContractEventsSubscription.test.js
- src/eventsRelay/index.js
- src/node.js
- src/period/checkBridge.js
- src/tx/applyTx/applyTx.test.js
- src/tx/applyTx/checkValidatorJoin.js
- src/tx/applyTx/checkValidatorLogout.js
- src/tx/applyTx/index.js
- src/txHelpers/activateSlot.js
- src/txHelpers/printTx.js
- src/txHelpers/submitPeriod.js
- src/utils/getAddress.js
- src/utils/hexToBase64.js
- src/utils/index.js
- src/utils/printStartupInfo.js
- src/utils/sendTransaction.js
- yarn.lock
> Store validators in app state

- src/block/updatePeriod.js
> Send activate tx in the right epoch

- index.js
- lotion/index.js
- src/api/jsonrpc.js
- src/node.js
> Added parsec_status method into JSON RPC

- src/cliArgs.js
> --preset cli option

- index.js
- nft-transfer.js
- package.json
- src/api/jsonrpc.js
- src/bridgeABI.js
- src/eventsRelay/index.js
- src/tx/applyTx/checkDeposit.js
- src/tx/applyTx/checkDeposit.test.js
- src/tx/applyTx/checkTransfer.test.js
- src/tx/applyTx/utils.js
- src/tx/applyTx/utils.test.js
- src/txHelpers/printTx.js
- src/utils/index.js
- tools/machine-gun.js
- tools/nft-transfer.js
- yarn.lock
> NFT Support

- src/api/methods/executeCall.js
- src/api/methods/executeCall.test.js
- src/api/methods/getBlockByHash.js
- src/api/methods/getBlockByHash.test.js
- src/api/methods/getBlockNumber.test.js
- src/api/methods/getColor.js
- src/api/methods/getColor.test.js
- src/api/methods/getColors.js
- src/api/methods/getColors.test.js
- src/api/methods/getConfig.test.js
- src/api/methods/getNodeStatus.test.js
- src/api/methods/getUnspent.test.js
- src/api/methods/txResponse.test.js
- src/utils/unspentForAddress.js
> JSON RPC api tests

- README.md
- docs/connect.md
- index.js
- src/readConfig.js
> Ability to fetch node config from another node

- .gitignore
- package.json
- src/api/methods/executeCall.js
- src/api/methods/executeCall.test.js
- src/api/methods/getBalance.test.js
- src/api/methods/getColors.js
- src/api/methods/getUnspent.js
- src/api/methods/getUnspent.test.js
- src/api/methods/txResponse.test.js
- src/block/addBlock.test.js
- src/block/updateValidators.test.js
- src/eventsRelay/ContractEventsSubscription.js
- src/tx/applyTx/checkConsolidate.test.js
- src/tx/applyTx/checkDeposit.test.js
- src/tx/applyTx/checkEpochLength.test.js
- src/tx/applyTx/checkExit.js
- src/tx/applyTx/checkExit.test.js
- src/tx/applyTx/checkTransfer.test.js
- src/tx/applyTx/checkValidatorJoin.test.js
- src/tx/applyTx/checkValidatorLogout.test.js
- src/tx/applyTx/utils.test.js
- src/utils/getAuctionedByAddr.test.js
- src/utils/getSlotsByAddr.test.js
- src/utils/handleEvents.test.js
- src/utils/readSlots.js
- src/utils/readSlots.test.js
> Enable coverage report on Jest. Increase test coverage

- index.js
- src/bridgeState.js
- src/cleanupLotion.js
Resolves #59 
Easier to change current behavior than add subcommand
> Stop node after cleaning up in lotion dir

- package.json
- src/tx/applyTx/checkConsolidate.js
- src/tx/applyTx/checkConsolidate.test.js
- src/tx/applyTx/checkTransfer.js
- src/tx/applyTx/checkTransfer.test.js
- src/tx/applyTx/utils.js
- src/tx/applyTx/utils.test.js
> Checking tx inputs and outputs with gas fees in mind

- package.json
- src/bridgeState.js
- src/bridgeState.test.js
- src/eventsRelay.js
- src/utils/ContractsEventsSubscription.js
- src/utils/ContractsEventsSubscription.test.js
- src/utils/__mocks__/ContractsEventsSubscription.js
- src/utils/handleEvents.js
> The one events subscription to rule them all

- package.json
- yarn.lock
Resolves #128 
Fixed here: https://github.com/leapdao/leap-core/pull/40
> fix: failed to serialize large denominations in outputs

- src/api/methods/sendRawTransaction.js
- src/api/methods/sendRawTransaction.test.js
Resolves: https://github.com/leapdao/leap-node/issues/150
> fix sendRawTx

- package.json
- yarn.lock
Resolves: https://github.com/leapdao/leap-node/issues/147
> fix event reader

- package.json
- src/api/methods/executeCall.js
- src/api/methods/getBalance.js
- src/api/methods/getBalance.test.js
- src/api/methods/txResponse.js
- src/api/methods/txResponse.test.js
- src/eventsRelay.js
- src/tx/applyTx/checkDeposit.js
- src/tx/applyTx/checkExit.js
- src/tx/applyTx/utils.js
- src/tx/applyTx/utils.test.js
- yarn.lock
related #157, leapdao/leap-core#48
> More JSBI/BigInt fixes

- src/tx/applyTx/checkDeposit.js
- src/tx/applyTx/checkDeposit.test.js
- src/tx/applyTx/checkTransfer.test.js
- src/tx/applyTx/utils.js
Proof and test of #143 
Tests for #145
> inflation and < 1 value tests

- src/tx/applyTx/checkDeposit.js
- src/tx/applyTx/utils.js
> check value correctly

- index.js
- src/api/methods/getConfig.js
- src/api/methods/getConfig.test.js
- src/bridgeState.js
- src/bridgeState.test.js
- src/tx/applyTx/checkTransfer.test.js
- src/utils/readConfig.js
- src/utils/readConfig.test.js
required for https://github.com/leapdao/bridge-ui/issues/128
> expose event buffer delays via getConfig JSON RPC, use 0 as default

- src/utils/cliArgs.js
> Fix --version

- package.json
- yarn.lock
Use this https://github.com/leapdao/tendermint-node/pull/1
> set infinite RPC sync timeout

- package.json
- src/utils/claimRewards.js
- yarn.lock
resolves: https://github.com/leapdao/leapdao/issues/56
use:
```
PROVIDER_URL=https://rinkeby.infura.io VALIDATOR_PRIV=0xaa..bb 
SWAP_ADDR=0x4f50FBe11eaF07EaEaC597A833A569cf09d5025f 
OP_CONTRACT_ADDR=0x65eFD41195062CB1f3FA65E3106F986a0A9cF726 
FROM_HEIGHT=3804908
TO_HEIGHT=3815351
node src/utils/claimRewards.js
```
> claim period rewards

- package.json
- yarn.lock
similar to https://github.com/leapdao/bridge-ui/issues/173
> pin etheriumjs-util version

- src/utils/claimRewards.js
found some bugs while claiming latest rewards
> fix rewards script a bit

- src/utils/getRootGasPrice.js
- src/utils/getRootGasPrice.test.js
- src/utils/sendTransaction.js
> use 'fast' gas price from EthGasStation when sending txs

- index.js
- src/api/jsonrpc.js
- src/api/methods/index.js
- src/api/methods/sendRawTransaction.js
- src/api/methods/sendRawTransaction.test.js
- src/eventsRelay.js
- src/txHelpers/sendTx.js
- tools/nft-transfer.js
Skipping lotion, sending to tendermint directly. One more step to deprecate txServer.
> do not use txServer for sendTx

- src/abis/bridgeAbi.js
- src/abis/operator.js
Fixes https://github.com/leapdao/leap-contracts/issues/131
Added changes that correspond to the changes in [leapdao/leap-contracts](https://github.com/leapdao/leap-contracts) made by https://github.com/leapdao/leap-contracts/pull/143 (merging the two events `Submission` and `NewHeight`).
> updated ABIs

- index.js
- presets/leap-mainnet.json
- src/tx/applyTx/checkSpendCond.js
- src/tx/applyTx/checkSpendCond.test.js
- src/tx/applyTx/index.js
- src/tx/index.js
> add noSpendingConditions network config option

- lotion/index.js
- lotion/lib/tendermint.js
Obvsly, it makes no sense to keep running without tendermint ;)
Fixes #209
> process.exit(1) if tendermint crashes

- .config.json
- README.md
- presets/leap-mainnet.json
- presets/leap-testnet-alpha.json
- presets/leap-testnet-beta.json
- presets/leap-testnet-gamma.json
- presets/leap-testnet.json
- src/api/methods/getConfig.js
- src/api/methods/getConfig.test.js
- src/bridgeState.js
- src/utils/index.js
- src/utils/networks.js
part of https://github.com/leapdao/bridge-ui/issues/188
> expose root networkId in config

- src/bridgeState.js
- src/utils/networks.js
> fix(bridgeState): use v3 infura URLs for root network provider

- src/api/createDb.js
- src/txHelpers/submitPeriod.js
- src/txHelpers/submitPeriod.test.js
Found during verification of #104 thought the reason is different and introduced recently [here](https://github.com/leapdao/leap-node/pull/204)
> fix(period): validator fails to resubmit the very first period

- package.json
- yarn.lock
Related https://github.com/leapdao/tendermint/issues/3
> use tendermint v0.31.0-leap.3

- src/api/methods/getBlockByHash.js
- src/api/methods/getBlockByHash.test.js
> fix(rpc): make getBlock response Ethers-compatible

- src/api/methods/getConfig.js
- src/api/methods/getConfig.test.js
> feat(rpc): return node version in getConfig response

- src/api/methods/getUnspent.test.js
- src/utils/filterUnspent.js
> Allow color to be a string in getUnspent

- package.json
- yarn.lock
Issue: https://github.com/axios/axios/issues/1098
> fix: bump vulnerable axios version

- package.json
- src/api/methods/getUnsignedTransferTx.test.js
- yarn.lock
Conforming with changes from leapdao/leap-core#127
> tests: fix for newer leap-core with to/from/value in toJSON()

- package.json
- yarn.lock
> fix: bump lodash to fix security issue

- src/tx/applyTx/checkSpendCond.js
- src/tx/applyTx/checkSpendCond.test.js
resolves https://github.com/leapdao/leap-node/issues/265
> display details about reverted execution

- src/tx/applyTx/checkSpendCond.js
- src/tx/applyTx/checkSpendCond.test.js
resolves #304 
resolves https://github.com/leapdao/leap-node/issues/311
> invalid contract executions

- src/abis/exitHandler.js
related to ABI changes in this PR: https://github.com/leapdao/leap-contracts/pull/239
> update ExitStarted ABI

- src/block/index.js
Resolves #313 
Verified with integration tests
> feat: cleanup votes for the submitted periods

- src/api/createDb.js
- src/api/methods/getTransactionReceipt.js
- src/api/methods/getTransactionReceipt.test.js
- src/block/addBlock.js
- src/bridgeState.js
- src/tx/applyTx/checkSpendCond.js
- src/tx/applyTx/checkSpendCond.test.js
resolves https://github.com/leapdao/leap-node/issues/314
> logs in getTxReceipt

- .travis.yml
- src/bridgeState.js
- src/bridgeState.test.js
- src/tx/applyTx/checkEpochLength.js
- src/tx/applyTx/checkEpochLength.test.js
- src/tx/applyTx/checkMinGasPrice.js
- src/tx/applyTx/checkMinGasPrice.test.js
Resolves #310
The problem was with this condition:
https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkEpochLength.js#L15-L20
In replay we already have all events processed by bridgeState, so the check always was false. I think we can safely remove it since we have this check bellow: https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkEpochLength.js#L22-L27
Also, I removed the same check from `checkMinGasPrice`
> Fix epochLength update

- src/abis/operator.js
- src/api/createDb.js
- src/api/createDb.test.js
- src/api/methods/getPeriodByBlockHeight.js
- src/api/methods/getPeriodByBlockHeight.test.js
- src/api/methods/index.js
- src/block/index.js
- src/block/updatePeriod.js
- src/bridgeState.js
- src/period/submitPeriodVote.test.js
- src/period/utils/checkEnoughVotes.test.js
- src/tx/applyTx/checkPeriodVote.test.js
Adds `plasma_getPeriodByBlockHeight` JSON RPC
Resolves #289
> feat: add period store

- src/api/methods/getUnsignedTransferTx.js
- src/api/methods/getUnsignedTransferTx.test.js
- src/api/methods/getUnspent.js
- src/api/methods/getUnspent.test.js
> feat: allow to pass address to getUnspent and getUnsignedTransferTx

- src/api/methods/getState.js
- src/api/methods/index.js
- src/api/methods/index.test.js
Exposing `bridgeState` object.
Accompanies #340
> feat: add plasma_getState RPC call

- presets/leap-testnet.json
> fix(config): add feature flags to testnet config

- DEVELOPMENT.md
- README.md
- added architectural overview
- restructured the file with focus on general public
- development and advanced configuration moved out to a separate file and docs.leapdao.org
Resolves #367
> docs: better README

- src/bridgeState.js
- src/utils/debug.js
`bridgeState` subscribes for events in plasma contracts to sync state. Here we want to add extra logging for these events.
> feat: log bridge events

- index.js
- src/api/methods/getUnspent.js
- src/api/methods/getUnspent.test.js
- src/heartbeat/defaults.js
- src/heartbeat/index.js
- src/heartbeat/index.test.js
- src/heartbeat/loop.js
- src/heartbeat/loop.test.js
- src/heartbeat/pulse.js
- src/heartbeat/pulse.test.js
Close #288
For the code review refer to #375
Reopening the PR to enable CI.
> Send heartbeat every minute

- src/bridgeState.js
- src/eventsRelay.js
Adds missing logging for bridge events. Continues work started in #373
> feat(log): log MinGasPrice, Validator* events

- package.json
- src/bridgeState.js
- yarn.lock
Uses updated leap-core. See leapdao/leap-core#169
Related https://github.com/leapdao/meta/issues/205
> fix: skipped deposits of NFT with zero value
