package.json
yarn.lock

Resolves #41 
Resolves #23 
I was wrong about `syncing`/`catching_up` flag value. `catching_up` really become `false` after the node synched up with peers (replayed to latest height), so we can use it for delaying execution of eventRelay (resolves #35).
My misunderstanding was caused by lack of Go knowledge and validators updates in `initChain`
Real changes here: https://github.com/parsec-labs/tendermint-node/commit/d2482525b976df771f44d7296d097d865d2ff62f

Node synchronization

---

.config.json
README.md
index.js
presets/leap-testnet-alpha.json
presets/leap-testnet-beta.json
src/api/methods/getConfig.js
src/api/methods/getConfig.test.js
src/utils/printStartupInfo.js

Calling `web3.eth.net.getId` for Leap provider fails with:
```
Invalid JSON RPC response: {"jsonrpc":"2.0","id":1}
```
Few things were not right here:
- `bridgeState.networkId` was always [set](https://github.com/leapdao/leap-node/blob/master/src/bridgeState.js#L31) to `undefined`.
- `net_version` (aka `net.getId`) is [supposed](https://web3js.readthedocs.io/en/1.0/web3-net.html#getid) to return numeric value
Solution:
Proposing `networkId` — unique numeric value to indicate networkId. 
Possible values: `1340` for mainnet, `1341` for testnet (`134` for LEA 😎)

fix: broken net_version JSON RPC method

---

src/api/methods/txResponse.js
src/api/methods/txResponse.test.js

https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransaction
So that we can create typedef extended from `web3/Transaction`

make getTransaction JSON RPC compatible with Web3

---

src/api/methods/sendRawTransaction.js
src/api/methods/sendRawTransaction.test.js

follow RPC specification

---

index.js
package.json
src/abis/exitHandler.js
src/bridgeState.js
src/bridgeState.test.js
src/eventsRelay.js
src/tx/applyTx/checkConsolidate.test.js
src/tx/applyTx/checkDeposit.test.js
src/tx/applyTx/checkMinGasPrice.js
src/tx/applyTx/checkMinGasPrice.test.js
src/tx/applyTx/checkTransfer.test.js
src/tx/applyTx/checkValidatorJoin.test.js
src/tx/applyTx/checkValidatorLogout.test.js
src/tx/applyTx/index.js
src/tx/applyTx/utils.js
src/tx/applyTx/utils.test.js
src/txHelpers/printTx.js
yarn.lock

related to https://github.com/leapdao/leap-contracts/issues/116
resolves https://github.com/leapdao/leap-node/issues/100

make MinGasPrice consensus param

---

src/tx/applyTx/checkExit.js
src/tx/applyTx/checkExit.test.js

`checkExit` used to fail for non-existing utxo (that's good), but because of `TypeError: Cannot read property \'address\' of undefined` (that's not good).
For example, here https://github.com/leapdao/leapdao-integ-tests/pull/8/files#diff-c545251c3884e9b6965f1ca3e4cbdcbaR42
This PR is to handle the situation properly

make checkExit to handle exiting non-existing utxo

---

Dockerfile
index.js
lotion/index.js
lotion/lib/tendermint.js
src/utils/cliArgs.js

This will allow to run unsafe RPC without exposing it to the public: `--tendermintAddr 127.0.0.1`
Required for https://github.com/leapdao/leap-node/issues/185

add --tendermintAddr option to set tendermint RPC host

---

Dockerfile
docker-compose.yml
index.js
lotion/index.js
lotion/lib/tendermint.js
package.json
src/utils/cliArgs.js
yarn.lock

Required for #185
~⚠️ This switches on `unsafeRpc` for tendermint, so make sure tendermint RCP is never exposed to the public internet~

Allow to run validator without producing blocks

---

src/api/methods/getColors.js

Fix for the second part of "DAI ruined the mainnet" problem.
Test for this fix: https://github.com/leapdao/integration-tests/pull/23
Related: https://github.com/leapdao/bridge-ui/pull/186, https://leapdao.slack.com/archives/CFQH2UH3Q/p1552316713000500

fix: getColors forgets about old tokens

---

presets/leap-testnet.json

> `validator-a` and `validator-b`
> - available only on private network
> - sharing the same validator key
> - public addresses: val1.testnet.leapdao.org, val2.testnet.leapdao.org
`9a8a32b074ccb2406360e770d3a6c0ed8693f67a@172.31.39.112:46691`
`08e6e74922cb0f1d3af8128f7befa4e6c1793480@172.31.24.196:46691`
> `sentinel-a` and `sentinel-b`
> - part of https://testnet-node1.leapdao.org/ load balancer
`ad05ba527e43d5d54e5202e062afa829d04ac779@sen1.testnet.leapdao.org:46691`
`c247bb928c8b5d1ee9777ddbc1260475c9c88286@sen2.testnet.leapdao.org:46691`
> - part of https://testnet.leap.whoot.me/ JSON RPC load balancer
> - sharing the same validator key
`95837e9c5cb9d90ac17b853f1a2d1fd8de5f5eb6@node-a.leap.whoot.me:46691`
`d3038ca78370acb23b8b433859d3a99aebedab4f@node-b.leap.whoot.me:46691`

explicitly add testnet peers

---

presets/leap-mainnet.json

two validator nodes (same validator key, intranet only)
two sentinel nodes (for JSON RPC scalability group)

explicitly add mainnet peers

---

index.js
src/block/index.js
src/block/updatePeriod.js
src/period/index.js
src/txHelpers/submitPeriod.js

ensure readonly node is not submitting periods and activation transactions. It assumed that readonly node is accompanied by writeable node with the same validator key, which does all the hustle.
TODO:

do not send activate and submitPeriod txs from readonly node

---

README.md
docker-compose.yml
index.js
setup/cloud/leap.systemd.service

- Enables the DevTools protocol on port 9999@localhost
- Readme example with ssh relay
- assign bridgeState and other useful things to `global`
Fixes #192

Remote debugging / profiling

---

src/bridgeState.js
src/txHelpers/submitPeriod.js
src/txHelpers/submitPeriod.test.js

First take. Addressing https://leapdao.slack.com/archives/CFKUNHHC7/p1552019049001600
resolves: https://github.com/leapdao/leap-node/issues/172
TODO:

don't submit period if no prev period root found

---

package.json

potential fix for
```
ubuntu@ip-172-31-31-90:~$ DEBUG=tendermint,leap-node* leap-node --config leap-testnet-theta.json --fresh
module.js:550
throw err;
^
Error: Cannot find module 'protobufjs/minimal'
...
at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/leap-node/lotion/abci/types.js:4:17)
...
at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/leap-node/lotion/abci/src/connection.js:7:31)
...
at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/leap-node/lotion/abci/src/server.js:5:20)
```

moved protobuf to deps

---

src/bridgeState.js
src/utils/getRootGasPrice.js
src/utils/getRootGasPrice.test.js

Appears on mainnet when ethGasStation returns fast estimate of 16.9 gwei
Error: [number-to-bn] while converting number 16899999999.999998 to BN.js instance
https://leapdao.slack.com/archives/CFQH2UH3Q/p1558088707002300

hotfix: gas price is not decimal

---

src/abis/bridgeAbi.js

to conform to 
https://github.com/leapdao/leap-contracts/pull/204
https://github.com/leapdao/leap-contracts/pull/206

feat: update bridge and operator abis

---

setup/cloud/leap.systemd.service

So we don't have to mess with files, log rotation etc. 
This is the right way to do logging as logs are streams, not files. Supporting link: https://12factor.net/logs
Read logs with `journalctl -t leap-node`.
Follow the tail with `journalctl -t leap-node -f`.

docs: log to STDOUT in reference systemd config

---

presets/leap-mainnet-v1.json
presets/leap-mainnet.json

Old mainnet config moved to leap-mainnet-v1.json
Highlights:
- spending conditions enabled!
- no `rootNetwork` param, which is long deprecated in favour of `rootNetworkId`
- two sentinels/sentries, one validator
- no shadow validator setup (dangerous, less needed now as we have faster restarts). Long term solution is to setup 4+ validators

docs: add network config for the new mainnet

---

src/tx/applyTx/checkSpendCond.js

make check spend condition fail if tx failed preserving [old behavior](https://github.com/leapdao/leap-node/pull/291/files#diff-b4471cf36ae8847d81e79bc7b9160f44R405).
Actually replacing `{ error: 'TypeError: Cannot read property \'vm\' of undefined' }` with `VmError { error: 'revert', errorType: 'VmError' }` 😂 
Details: https://leapdao.slack.com/archives/CFKUNHHC7/p1563400681015000

fix: rethrow error from EVM

---

presets/leap-testnet.json

- swapped sen1 and val2 hosts (validator was on sen1, now on val2 again)
- added Evgeni's validator
- removed val1 (not operating anymore)

chore: update testnet peer list in config

---

package.json
src/api/createDb.js
src/api/createDb.test.js
src/api/methods/getTransactionByPrevOut.js
src/api/methods/getTransactionByPrevOut.test.js
src/api/methods/getUnsignedTransferTx.test.js
src/api/methods/index.js
yarn.lock

Adds `plasma_getTransactionByPrevOut` RPC call. See usage below
Requires: https://github.com/leapdao/leap-core/pull/131
Resolves #283 
Possible test scenario:
1. Start a local leap network. [How](https://github.com/leapdao/integration-tests#start-local-environment-for-development)
2. Copy the funded priv key from local network console.
3. Send transfer tx with machine gun. [How](https://github.com/leapdao/leap-guardian#machine-gun)
Receipt:
```
{ to: '0xCED6Cec7891276E58d9434426831709fcBdD0C49',
from: '0xCED6Cec7891276E58d9434426831709fcBdD0C49',
contractAddress: null,
transactionIndex: 0,
gasUsed: BigNumber { _hex: '0x0' },
logsBloom: '0x',
blockHash:
'0x6c5114be8ee90289fe40e0e733c36ccf36c0b9fedc7eb3f0aba25f688497b050',
transactionHash: …
```

feat: index transactions by utxo they spend

---

README.md
index.js
lotion/index.js
src/utils/cliArgs.js

Added new optional CLI argument: `--dataPath` to specify where to store network data.
Maybe useful to run two nodes on the same machine without `devMode` and Docker.

feat(config): allow to specify data folder

---

index.js
package.json
src/abis/operator.js
src/block/index.js
src/block/updatePeriod.js
src/block/updatePeriod.test.js
src/bridgeState.js
src/eventsRelay.js
src/period/index.js
src/period/period.test.js
src/period/submitPeriodVote.js
src/period/submitPeriodVote.test.js
src/period/utils/checkEnoughVotes.js
src/tx/applyTx/checkPeriodVote.js
src/tx/applyTx/checkPeriodVote.test.js
src/tx/applyTx/index.js
src/tx/applyTx/utils.js
src/tx/applyTx/utils.test.js
src/txHelpers/delayedSender.js
src/txHelpers/printTx.js
src/txHelpers/submitPeriod.js
src/txHelpers/submitPeriod.test.js
src/utils/buildCas.js
src/utils/buildCas.test.js
src/utils/index.js
yarn.lock

feat: support period vote tx

---

src/abis/exitHandler.js
src/abis/operator.js

Resolves #324 
This solution may seem like a cheat comparing with bounty description, but:
1. It happens not so often to add a new complex system into the node. Less complexity, less bugs
2. Many things can be changed along with event signature and IMO we should think more about these cases, not about event decode
3. It may be a good idea to add a new event instead of changing the old one
With this PR events work fine, but i was not able to sync local node with testnet because of [this tx](https://testnet.leapdao.org/explorer/tx/0x26805fe0b0e1cf7ab4dfede7f19c76493b2ec9b4490a5b42ed467374b30b9b94). I've got `not touched 0x197970e48082cd46f277abdb8afe492bccd78300` error at height 43897 in tx handler (see 2.).
P. S.
Not quite sure what to do about bounty size 🤷‍♂ 
/cc @troggy

Add old events into ABIs

---

src/block/updatePeriod.js
src/block/updatePeriod.test.js
src/bridgeState.js
src/period/utils/checkEnoughVotes.js
src/txHelpers/submitPeriod.js
src/txHelpers/submitPeriod.test.js
src/utils/sendTransaction.js

- submission is done in a block handler, so that the node has time to collect votes
- temporary storing has of submission tx until it is mined. So that we don't submit same period twice
Resolves #309 
Requires #289 for client side to work with this change. Otherwise no data to construct CAS proofs

feat: submit period with CAS once got 2/3 of the votes.

---

src/tx/applyTx/checkEpochLength.js
src/tx/applyTx/checkEpochLength.test.js

So later on it can be exposed outside via plasma_getState.
Accompanies #340

feat: export epochLength in a bridgeState

---

src/utils/ContractsEventsSubscription.js

`ContractsEventsSubscription` class reads events in interval `[fromBlock,toBlock]` every root chain block. After each read, it does `fromBlock = toBlock` assignment, to continue reading from `toBlock`.
However, both boundaries are included in the iteration. So block at `toBlock` height is already been read within `[fromBlock,toBlock]` iteration. To read the next portion, we have to start from `toBlock + 1`, not from `toBlock`.
Relates #340

fix: event subscription code reads the same block twice.

---

package.json
src/bridgeState.js
src/bridgeState.test.js
src/eventsRelay.js
src/tx/applyTx/checkEpochLength.js
src/tx/applyTx/checkEpochLength.test.js
src/tx/applyTx/index.js
src/txHelpers/printTx.js
yarn.lock

Requires: leapdao/leap-core#155, #348
Resolves #340 
Test to reproduce with: leapdao/integration-tests#69
Tendermint has a [build-in replay protection](https://tendermint.com/docs/app-dev/app-development.html#replay-protection) which will reject the same tx from being added to the mempool twice. It seems to work by comparing raw tx bytes. Should two transactions have the same raw bytes, the second one will not make it to the mempool.
Now, EpochLength transaction in leap-core is merely a `[type,epochLength]` tuple. `Tx.epochLength(X)` will have the same raw bytes for the same `X`. Consider the following pretty valid transaction flow:
```
1. Tx.epochLength(2)
2. Tx.epochLength(4)
3. Tx.epochLength(2)
```
The third transaction will be rejected by tendermint's replay protection.
The node …

fix: node skips some epoch length txs making bridgeState corrupt

---

src/api/methods/getUnspent.js
src/api/methods/getUnspent.test.js
src/bridgeState.js
src/bridgeState.test.js
src/tx/applyTx/checkExit.js
src/tx/applyTx/checkExit.test.js
src/utils/ContractsEventsSubscription.js
src/utils/ContractsEventsSubscription.test.js
src/utils/__mocks__/ContractsEventsSubscription.js

Resolves #284 
- add additional handling for `ExitStarted` event: no consensus delay, store exiting utxos in a bridge state
- filter exiting utxos from the results of `getUnspent` RPC
---
Possible way to verify:
1. Run local env using this PR branch for leap-node (`yarn start` in integration tests)
2. push chain to the next period (block 36)
3. Run local bridge UI and start an exit.
4. Notice that the exited UTXO disappears before Exit transaction is included. Increase bridge delay (e.g. add `BRIDGE_DELAY: 20` [here](https://github.com/leapdao/integration-tests/blob/master/src/run.js#L38)) to slow down Exit tx inclusion if needed.

feat: exclude exiting utxos from active utxo set

---

lotion/lib/abci-app.js
src/block/updatePeriod.js
src/block/updatePeriod.test.js
src/period/index.js
src/period/period.test.js

Due to the [bug](https://github.com/leapdao/tendermint/pull/10) in our tendermint fork, `chainHeight` is always 0 in a period handler. We didn't use it though for some reason and took block height from `chainInfo` instead. However, it was changed in April and we missed the fact that `chainHeight` is always 0, thus making checkBridge ABCI to always succeed without checking anything.
As a a side effect, all the CAS-related changes in period handler were never called and thus never tested in a wild.
Resolves #326 
In checkBridge we don't want to check periods which don't have enough votes and hence not yet submitted.
I propose to track those as `pendingPeriod`.
Every 32nd block we want to:
1. keep the current period as `pendingPeriod` until we collect enough votes
2. start a new period right …

fix: check bridge always return success

---

README.md
index.js
src/utils/cliArgs.js
src/utils/readConfig.js
src/utils/readConfig.test.js

Follow up for #353 
/cc @vrde 
Allows to do things like (needed for https://github.com/leapdao/integration-tests/issues/54):
```
curl -O https://raw.githubusercontent.com/leapdao/leap-node/master/presets/leap-testnet.json
leap-node --config=./leap-testnet.json --rootNetwork=https://rinkeby.infura.io/v3/XXXXXX
```

feat: add rootNetwork CLI arg

---

src/block/updatePeriod.js
src/txHelpers/submitPeriod.js

We were prematurely marking the period as submitted (in updatePeriod) — at [this](https://github.com/leapdao/leap-node/compare/fix/submit-period?expand=1#diff-786c9ee7cb87a989994653f4a23150a6L29) point period submission may not happen yet and may never happen (e.g. due to error).
The code which was supposed to do that in `submitPeriod` was [broken](https://github.com/leapdao/leap-node/compare/fix/submit-period?expand=1#diff-8372d553eb3845a04d491ab410b2620aR112) and [never really called](https://github.com/leapdao/leap-node/compare/fix/submit-period?expand=1#diff-8372d553eb3845a04d491ab410b2620aR111).
Additionally, logging period submission errors now.

fix: proper error handling for period submission.

---

src/utils/getCurrentSlotId.js
src/utils/getCurrentSlotId.test.js

Each active slot becomes proposer at least once per epoch.
See unit tests for fixtures.
Resolves #364
Resolves #31

fix: proper slot selection

---

src/block/index.js
src/block/updatePeriod.js
src/block/updatePeriod.test.js
src/period/utils/isReplay.js

State was saved every 32nd block once 32nd block is processed, so on restart currentPeriod is blank and being filled with blocks starting from 33rd and so on.
Proposed solution is to save state before we process 32nd block, thus it will be "replayed" on restart producing correct currentPeriod object. This requires some replay protection for period vote and period submission code triggered every 32nd block as well (implemented here as well)
🍝 
Resolves #366

fix: restarting the validator skips x32nd block from the currentPeriod

---

src/validator/periods/submitPeriod.js
src/validator/periods/submitPeriod.test.js

Plasma bridge [requires](https://github.com/leapdao/leap-contracts/pull/264/files#diff-a1c254046ad1d0b9aadb7ff8be8273afR452) **strictly** a minimum amount of sigs to be submitted. Otherwise, reverts. This PR adjusts period submission for that.
Related: leapdao/meta#199
Resolves #386

fix(periods): submit only quorum of CAS signatures

---

src/validator/periods/checkEnoughVotes.js
src/validator/periods/checkEnoughVotes.test.js

We want to calculate CAS quorum using the number of _active_ slots only, not epochLength. See leapdao/meta#199 for background.

fix: checkEnoughVotes should account for slot gaps

---

package.json
src/utils/sendTransaction.js
yarn.lock

If given `method` call fails (e.g. tx reverts), `estimateGas` will fail as well.
If not caught, this exception will pop up out of ABCI handler and thus terminate the node process.
Proposed solution: catch the exception and return rejecting PromiEvent.

fix: handle failing calls to sendTransaction

---

src/bridgeState.js
src/validator/periods/startNewPeriod.js
src/validator/periods/startNewPeriod.test.js

We keep the app state, so we don't need to replay everything from the genesis. However,
we kept rereading all the root chain events on each restart. Proposed change: store the last
root chain height processed and resume the sync from that height on restart.
Accompanying change:
- storing period proposals not every block, but once created (every 32 blocks)
Resolves #384

feat: start root chain sync from the last app state

---

lotion/bin/download.js

`download.js` script fails to determine platform in some cases and thus fails to download tendermint
FYI @roleengineer

fix(build): fix tendermint download for some x32 platforms

---

src/heartbeat/pulse.js

Two problems fixed:
- `getUnspent` is async and thus returns Promise. Fixed by `await`ing.
- there are both `heartbeatColor` and `heartbeat.color` config options. Fixed by using only the latter

fix(heartbeat): heartbeat service is not submitting txs

---

src/txHelpers/makeTransfer.js
src/utils/getRootGasPrice.test.js

Please remember the [Contributing Guidelines](https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md) :heart:
- Resolves #350 by changing `helpers.calcOutputs` to `Tx.calcOutputs` and so on. 
- Mocks web3 in getRootGasPrice unit tests, so that real provider is not used.
Closes #350

fix: remove deprecated calls and improve unit tests

---

.eslintrc
package.json
src/api/createDb.js
src/api/jsonrpc.js
src/api/methods/executeCall.js
src/api/methods/getBalance.js
src/eventsRelay.js
src/tx/applyTx/checkDeposit.js
src/tx/applyTx/checkExit.js
src/tx/applyTx/checkMinGasPrice.js
src/tx/applyTx/checkSpendCond.js
src/tx/applyTx/utils.js
src/tx/applyTx/utils.test.js
src/utils/buildCas.js
src/utils/buildCas.test.js
yarn.lock

Please remember the [Contributing Guidelines](https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md) :heart:
- replace all the JSBI arithmetics with native BigInt
- use BigInt literals everywhere possible (e.g. `12n` instead of `BigInt(12)`)
- bumped `jest` version. Newer version uses latest babel with BigInt support
Nothing special: unit tests, integration tests. Everything should be done automatically
Requires https://github.com/leapdao/leap-core/pull/173 (released temporary as leap-core@3.0.0-beta.0)
Closes #414

feat: use native BigInt instead of JSBI

---

src/period/index.js
src/utils/getActiveSlots.js
src/utils/getCurrentSlotId.js
src/validator/periods/checkEnoughVotes.js
src/validator/periods/checkEnoughVotes.test.js

This PR fixes the following issue:
If validator is logged out, but not yet removed from validator set (activation pending), we
need to consider it as non-slot for CAS quorum calculations. Otherwise, plasma rejects the period submission.
E.g. for a validator set of size 5, CAS quorum is 4 (4 votes needed for period submission). However, if one of these validators are in process of logging out, the CAS quorum should be 3 (as if the validator set is of size 4).
We are not logging out validator right away, but rather keep them in the validator set marked as subject for removal. It is needed to give everyone time to possibly challenge this validator.
examine unit tests
if you feel adventurous you may set up a local network with 5 validators and log one of them out. Though cumbersome and not …

fix(validator): CAS quorum should take logged out slots into account.
